spring:
  application:
    name: ghostrip

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        highlight_sql: true
        generate_statistics: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/ghostrip?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:95206326}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ghostrip-bucket
        exp-time: 300000  # presigned URL 유효시간 (ms) = 5분

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    doc-expansion: none
    persist-authorization: true
    tags-sorter: alpha
